# Copyright Â© 2023 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

name: OpenIM Dependency Review
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check Repository Settings'
        run: |
          DEPENDENCY_GRAPH_ENABLED=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/settings | jq .dependency_graph)
          ADVANCED_SECURITY_ENABLED=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/settings | jq .advanced_security)
          if [ "$DEPENDENCY_GRAPH_ENABLED" != "true" ] || [ "$ADVANCED_SECURITY_ENABLED" != "true" ]; then
            echo "Error: Dependency graph and/or GitHub Advanced Security are not enabled on this repository. Please enable them in the repository settings."
            exit 1
          fi
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3